(() => {
  if (window.__fx3PipExecutionLoaded) return;
  window.__fx3PipExecutionLoaded = true;

  const EXECUTION_TARGET_PIPS = 3.0;
  const FEATURE_TARGET_REF = 5.1911590909;
  const HOLDOUT_2026_TARGET_HIT = 88.61;
  const HOLDOUT_2026_FIRST_TOUCH = 66.37;
  let model3 = null, baseModel = null, macroContext = null;
  let slowCache = null, slowCacheAt = 0, busy = false, lastKey = '';

  const NOTE_TEXT = `判定は15分ごとの確定ポイントで更新します。3pipライブ確率と約5pipライブ確率は、同じ47特徴（複数時間足・EMA・RSI・ATR・モメンタム・過去到達率・時間帯・日米金利差・米10年/2年金利など）を使用します。方向モデルも共通で、違うのは到達モデルの学習目標だけです。3pipモデルは30分以内±3pip、5pipモデルは約5.19pipを学習しています。「3pip到達率（検証）」${HOLDOUT_2026_TARGET_HIT.toFixed(2)}% は、2026年7月1日〜8月14日のシグナル562件で予測方向へ3pip届いた過去実績です。逆方向3pipより先に届いた割合は ${HOLDOUT_2026_FIRST_TOUCH.toFixed(2)}%。将来の成績を保証するものではありません。`;

  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const sigmoid=x=>1/(1+Math.exp(-clamp(x,-40,40)));
  function setTextIfNeeded(el,text){if(el&&el.textContent!==text)el.textContent=text;}
  function ema(v,n){if(!v.length)return NaN;const a=2/(n+1);let e=v[0];for(let i=1;i<v.length;i++)e=v[i]*a+e*(1-a);return e;}
  function rsi(v,n=14){if(v.length<n+1)return 50;let g=0,l=0;for(let i=v.length-n;i<v.length;i++){const d=v[i]-v[i-1];g+=Math.max(d,0);l+=Math.max(-d,0);}return l===0?100:100-100/(1+(g/n)/(l/n));}
  function atr(bs,n=14){if(bs.length<n+1)return 0;let s=0;for(let i=bs.length-n;i<bs.length;i++){const b=bs[i],p=bs[i-1].c;s+=Math.max(b.h-b.l,Math.abs(b.h-p),Math.abs(b.l-p));}return s/n;}
  function aggregate(bs,min){const ms=min*60000,m=new Map();for(const b of bs){const k=Math.floor(b.t/ms)*ms;let x=m.get(k);if(!x){x={t:k,o:b.o,h:b.h,l:b.l,c:b.c};m.set(k,x);}else{x.h=Math.max(x.h,b.h);x.l=Math.min(x.l,b.l);x.c=b.c;}}return[...m.values()].sort((a,b)=>a.t-b.t);}
  function tfScore(bs){if(!bs||bs.length<25)return 0;const c=bs.map(x=>x.c),e9=ema(c.slice(-40),9),e21=ema(c.slice(-60),21),rr=rsi(c),mom=c.at(-1)-c.at(-4);let s=(e9>e21?1:-1)+(c.at(-1)>e9?.6:-.6)+(mom>0?.5:-.5)+(rr>52?.5:rr<48?-.5:0);if(rr>75)s-=.35;if(rr<25)s+=.35;return clamp(s/2.6,-1,1);}
  function historicalReach(bs){if(bs.length<80)return{long:.5,short:.5};const d=FEATURE_TARGET_REF*.01;let L=0,S=0,N=0;for(let i=Math.max(0,bs.length-360);i<bs.length-30;i+=2){const base=bs[i].c;let u=false,dn=false;for(let j=i+1;j<=i+30;j++){u ||= bs[j].h>=base+d;dn ||= bs[j].l<=base-d;}L+=u?1:0;S+=dn?1:0;N++;}return{long:N?L/N:.5,short:N?S/N:.5};}
  function pos(c,n){const z=c.slice(-n),lo=Math.min(...z),hi=Math.max(...z),last=c.at(-1);return hi>lo?(last-lo)/(hi-lo):.5;}
  const utcDate=ms=>new Date(ms).toISOString().slice(0,10);
  function treasuryFeatures(ctx,t){const rows=(ctx?.dgs10||[]).filter(x=>x.date<utcDate(t));if(!rows.length)return[0,0,0,0];const y=Number(rows.at(-1).value),y1=Number((rows.at(-2)||rows.at(-1)).value),y5=Number((rows.at(-6)||rows[0]).value);return[y/5,(y-y1)*10,(y-y5)*2,((y-y1)-(y1-y5)/5)*5];}
  function eventFeatures(ctx,t){const one=(arr,pre,post)=>{const ev=(arr||[]).map(x=>Date.parse(x)).filter(Number.isFinite);if(!ev.length)return[0,0];const ds=ev.map(x=>(x-t)/60000),near=ds.reduce((a,b)=>Math.abs(a)<Math.abs(b)?a:b),active=near>=-post&&near<=pre?1:0;return[active,active?clamp(near/Math.max(pre,post),-1,1):0];};const c=one(ctx?.events?.cpi,120,120),n=one(ctx?.events?.nfp,120,120),f=one(ctx?.events?.fomc,180,180),all=[...(ctx?.events?.cpi||[]),...(ctx?.events?.nfp||[]),...(ctx?.events?.fomc||[])].map(Date.parse).filter(Number.isFinite);let near=999999;if(all.length)near=all.map(x=>(x-t)/60000).reduce((a,b)=>Math.abs(a)<Math.abs(b)?a:b);return[...c,...n,...f,Math.abs(near)<=60?1:0,Math.abs(near)<=180?1:0];}
  function lagCalendar(rows,t,daysBack){if(!rows?.length)return 0;const d=new Date(t);d.setUTCDate(d.getUTCDate()-daysBack);const key=d.toISOString().slice(0,10),z=rows.filter(x=>x.date<=key);return Number((z.at(-1)||rows[0]).value)||0;}
  function precisionMacro(model,ctx,t){const d2=model?.dgs2||[],d10=ctx?.dgs10||[],y2=lagCalendar(d2,t,1),y22=lagCalendar(d2,t,2),y26=lagCalendar(d2,t,6),y10=lagCalendar(d10,t,1),y102=lagCalendar(d10,t,2);return[y2/5,(y2-y22)*10,(y2-y26)*5,y10-y2,(y10-y102)*10];}
  function features(series,ctx,cutoff,model){const trim=bs=>bs.filter(x=>x.t<=cutoff),s={m1:trim(series.m1),m5:trim(series.m5),m15:trim(series.m15),h1:trim(series.h1),h4:trim(series.h4),d1:trim(series.d1)},scores=[tfScore(s.m1),tfScore(s.m5),tfScore(s.m15),tfScore(s.h1),tfScore(s.h4),tfScore(s.d1)],h=s.m1,c=h.map(x=>x.c),last=c.at(-1),hist=historicalReach(h),ap=atr(h)/.01,rr=rsi(c),scale=FEATURE_TARGET_REF*.01,e9=ema(c.slice(-60),9),e21=ema(c.slice(-80),21),e50=ema(c.slice(-100),50),h20=h.slice(-20),h60=h.slice(-60),rng20=Math.max(...h20.map(x=>x.h))-Math.min(...h20.map(x=>x.l)),rng60=Math.max(...h60.map(x=>x.h))-Math.min(...h60.map(x=>x.l)),moms=[1,3,5,10,15,30,60].map(n=>c.length>n?(last-c[c.length-1-n])/scale:0),dt=new Date(cutoff),hour=dt.getUTCHours()+dt.getUTCMinutes()/60,ang=2*Math.PI*hour/24,dow=(dt.getUTCDay()+6)%7,dang=2*Math.PI*dow/5,rateDiff=Number(ctx?.policy?.diff??2.625),base=[...scores,hist.long,hist.short,hist.long-hist.short,ap/FEATURE_TARGET_REF,(rr-50)/25,(last-e9)/scale,(e9-e21)/scale,(e21-e50)/scale,pos(c,20)-.5,pos(c,60)-.5,rng20/scale,rng60/scale,...moms,Math.sin(ang),Math.cos(ang),Math.sin(dang),Math.cos(dang),rateDiff/3];return[...base,...treasuryFeatures(ctx,cutoff),...eventFeatures(ctx,cutoff),...precisionMacro(model,ctx,cutoff)];}
  function logistic(m,x){let z=m.intercept;for(let i=0;i<x.length;i++)z+=((x[i]-m.mean[i])/(m.scale[i]||1))*m.coef[i];return sigmoid(z);}

  async function loadModels(){if(model3&&baseModel&&macroContext)return;const[a,b,c]=await Promise.all([fetch('./fx-model-3pip-same47.json?v=27',{cache:'no-store'}),fetch('./fx-model.json?v=4',{cache:'no-store'}),fetch('./macro-context.json?v=1',{cache:'no-store'})]);if(!a.ok||!b.ok||!c.ok)throw new Error('3pip inputs');model3=await a.json();baseModel=await b.json();macroContext=await c.json();if(model3.feature_count!==47||baseModel.feature_count!==47)throw new Error('feature count');}
  async function fetchYahoo(interval,range){const hosts=['query1.finance.yahoo.com','query2.finance.yahoo.com'];let last;for(const host of hosts){try{const u=`https://${host}/v8/finance/chart/JPY=X?interval=${interval}&range=${range}&includePrePost=true&events=div%2Csplits`,r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));const j=await r.json(),z=j?.chart?.result?.[0],q=z?.indicators?.quote?.[0],ts=z?.timestamp||[],bars=[];for(let i=0;i<ts.length;i++){const o=Number(q.open?.[i]),h=Number(q.high?.[i]),l=Number(q.low?.[i]),c=Number(q.close?.[i]);if([o,h,l,c].every(Number.isFinite))bars.push({t:ts[i]*1000,o,h,l,c});}if(bars.length<25)throw new Error('few bars');return bars;}catch(e){last=e;}}throw last||new Error('fetch failed');}
  async function fetchSeries(){const m1=await fetchYahoo('1m','1d'),now=Date.now();if(!slowCache||now-slowCacheAt>300000){const[m5,m15,h1,d1]=await Promise.all([fetchYahoo('5m','5d'),fetchYahoo('15m','1mo'),fetchYahoo('60m','3mo'),fetchYahoo('1d','1y')]);slowCache={m5,m15,h1,d1,h4:aggregate(h1,240)};slowCacheAt=now;}return{m1,...slowCache};}
  const decisionCutoff=m1=>(m1.filter(b=>Math.floor(b.t/60000)%15===0).at(-1)||m1.at(-1)).t;

  function ensureCards(panel){const grid=panel.querySelector('.fxa-grid');if(!grid)return;let live=document.getElementById('fxa3PipLiveCard');if(!live){live=document.createElement('div');live.id='fxa3PipLiveCard';live.className='fxa-card';live.innerHTML='<div class="fxa-label">3pip到達確率（ライブ・47特徴）</div><div class="fxa-value neutral" id="fxa3PipLive">--%</div>';const reach=document.getElementById('fxaReach')?.closest('.fxa-card');if(reach)grid.insertBefore(live,reach);else grid.appendChild(live);}let val=document.getElementById('fxa3PipValidationCard');if(!val){val=document.createElement('div');val.id='fxa3PipValidationCard';val.className='fxa-card';val.innerHTML=`<div class="fxa-label">3pip到達率（検証）</div><div class="fxa-value good" id="fxa3PipValidation">${HOLDOUT_2026_TARGET_HIT.toFixed(2)}%</div>`;if(live.nextSibling)grid.insertBefore(val,live.nextSibling);else grid.appendChild(val);}setTextIfNeeded(document.getElementById('fxa3PipValidation'),`${HOLDOUT_2026_TARGET_HIT.toFixed(2)}%`);}
  function decorate(){const panel=document.getElementById('fxAnalysisPanel');if(!panel)return false;setTextIfNeeded(document.getElementById('fxaTarget'),`${EXECUTION_TARGET_PIPS.toFixed(1)} pips`);ensureCards(panel);panel.querySelectorAll('.fxa-label').forEach(label=>{if(label.textContent.includes('本日の目標相当'))setTextIfNeeded(label,'実運用の利確目安');else if(label.textContent.includes('30分以内の到達しやすさ')||label.textContent.includes('シグナル強度（5.19pip学習基準）'))setTextIfNeeded(label,'約5pip到達確率（ライブ・47特徴）');});setTextIfNeeded(panel.querySelector('.fxa-note'),NOTE_TEXT);const reasons=document.getElementById('fxaReasons');if(reasons&&!reasons.querySelector('[data-fx3pip]')){const chip=document.createElement('span');chip.className='fxa-chip up';chip.dataset.fx3pip='1';chip.textContent='利確目安 3.0pip';reasons.appendChild(chip);}return true;}
  function setLive(p){const el=document.getElementById('fxa3PipLive');if(!el)return;if(p==null){setTextIfNeeded(el,'--%');return;}setTextIfNeeded(el,`${Math.round(p*100)}%`);el.classList.remove('good','neutral','bad');el.classList.add(p>=.7?'good':p>=.5?'neutral':'bad');}
  async function updateLive(){if(busy)return;busy=true;try{if(!decorate())return;await loadModels();const series=await fetchSeries(),cutoff=decisionCutoff(series.m1),key=String(cutoff);if(key!==lastKey||document.getElementById('fxa3PipLive')?.textContent==='--%'){const x=features(series,macroContext,cutoff,baseModel);if(x.length!==47)throw new Error(`3pip feature mismatch ${x.length}`);setLive(logistic(model3.reach,x));lastKey=key;}}catch(e){console.warn('3pip same47',e);setLive(null);}finally{busy=false;}}
  function start(){if(!decorate()){setTimeout(start,250);return;}updateLive();setInterval(updateLive,15000);setInterval(decorate,2000);}
  start();
})();